# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: How to Data
email: ncarter@bentley.edu
description: >- # this means to ignore newlines until "baseurl:"
  Reference site for common computing tasks in statistics and data science
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://how-to-data.org" # the base hostname & protocol for your site
twitter_username: nathancarter5
github_username:  nathancarter

# Build settings
theme: just-the-docs
source: jekyll-input
destination: docs
# plugins:
#   - jekyll-feed

# Appearance
compress_html:
  ignore:
    envs: all  # necessary workaround to get code line numbers
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
color_scheme: my_colors

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - ./gemfiles/
  - ./Gemfile
  - ./Gemfile.lock
  - ./database/
  - .devcontainer/
  - ./build*.py
  - ./docs/
  - ./resources/
  - ./examples/
  # - assets/
  - .vscode/
  - __pycache__/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
