baseURL = "http://nathancarter.github.io/how2data/public/"
languageCode = "en-us"
title = "How To Data"
theme = "learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON" ]

# parameter specific to the Learn theme
[params]
  author = "Nathan Carter, ncarter@bentley.edu"
  description = "Reference site for common computing tasks in statistics and data science"
  disableLandingPageButton = false
  disableMermaid = true
  themeVariant = "blue"